vechain/thor-e2e-tests

.gitignore, jest.config.ts, package.json, yarn.lock
=> html report

README.md, jest.config.ts, network/docker-compose-base.yaml, network/docker-compose-solo.yaml, package.json, src/constants.ts, test/evm/eth-opcodes.test.ts, test/evm/individual-opcodes.test.ts, test/evm/paris/simple-paris.test.ts, test/thorest-api/accounts/execute-codes.test.ts, test/thorest-api/accounts/get-account-code.test.ts, test/thorest-api/accounts/get-account-storage.test.ts, test/thorest-api/accounts/get-accounts.test.ts, test/thorest-api/blocks/get-blocks.test.ts, test/thorest-api/logs/query-events.test.ts, test/thorest-api/logs/query-transfers.test.ts, test/thorest-api/node/get-peers.test.ts, test/thorest-api/subscriptions/ws-beat2.test.ts, test/thorest-api/subscriptions/ws-blocks.test.ts, test/thorest-api/subscriptions/ws-events.test.ts, test/thorest-api/subscriptions/ws-transfers.test.ts, test/thorest-api/subscriptions/ws-tx-pool.test.ts, test/thorest-api/transactions/get-transaction-receipt.test.ts, test/thorest-api/transactions/get-transaction.test.ts, test/thorest-api/transactions/post-transaction.test.ts, yarn.lock
- Add groups to tests
- Use same genesis file for solo & custom net
=> chore: use common genesis.json for solo and custom net

test/thorest-api/logs/query-events.test.ts, test/thorest-api/logs/query-transfers.test.ts
This PR fixes the API calls for PR https://github.com/vechain/thor/pull/777
=> chore: fix api logs limits

contracts/AuthorizeTransaction.sol, contracts/SimpleCounter.sol, contracts/Stringer.sol, src/contracts/hardhat.ts, src/wallet.ts, test/thorest-api/accounts/contracts.test.ts
Closes:
- #233
- #237
- #234
- #241
Link to tickets: https://github.com/orgs/vechain/projects/22/views/1?filterQuery=-label%3A%22App%3A+Nodes%22+assignee%3Adarrenvechain+label%3A%22Type%3A+Testing%22
=> feat: add contract testing

src/utils/methods-utils.ts, src/wallet.ts, test/thorest-api/transactions/dependant-transaction.test.ts, test/thorest-api/transactions/setup/multiple-transactions-data-driven-flow.ts, test/thorest-api/transactions/setup/transaction-data-driven-flow.ts
This PR refers to this [gh-issue](https://github.com/vechain/protocol-board-repo/issues/238).
=> Dependent transactions - positive

.github/workflows/run-e2e-tests.yaml, network/docker-compose-base.yaml, network/docker-compose-solo.yaml, network/docker-compose.yaml, package.json
=> chore: add docker logs

.github/workflows/run-e2e-tests.yaml, network/docker-compose-base.yaml, network/docker-compose.yaml
- added success to gha
- increased cpus / ram
=> chore: tune docker and gha

test/thorest-api/subscriptions/ws-beat2.test.ts
This PR is related to this [ticket](https://github.com/vechain/protocol-board-repo/issues/276).
=> New tests for beats2 websocket subscription

contracts/SimpleTransfer.sol, src/account-faucet.ts, src/thor-client.ts, test/thorest-api/subscriptions/ws-transfers.test.ts
PR addresses [this](https://github.com/orgs/vechain/projects/22/views/1?filterQuery=e2e&pane=issue&itemId=72240898) issue. For the negative path I added an optional `errorCallBack` to the `thorClient`. Also to test for a valid sender I added the option to inject the wallet to the `fundAccount` function but let me know if you have better ideas on how to do this.
=> Added transfer subscription tests

.github/workflows/biuld-lint.yaml, .github/workflows/lint.yaml, src/test-env.ts, src/thor-client.ts, test/thorest-api/subscriptions/ws-tx-pool.test.ts
[Issue](https://github.com/vechain/protocol-board-repo/issues/289)
=> Add linter when pushing commit

src/utils/legacy-bloom.ts, test/thorest-api/subscriptions/ws-beat.test.ts
This refers to this [issue](https://github.com/vechain/protocol-board-repo/issues/277).
=> Add beat test

test/evm/individual-opcodes.test.ts
- BASEFEE opcode
- contract starting with 0xEF
=> test: test for pre-shanghai

network/docker-compose-solo.yaml, test/evm/individual-opcodes.test.js, test/thorest-api/debug/tracers-call.test.js, test/thorest-api/debug/tracers.test.js
Tests for PR vechain/thor#833, needs to be merged before upstream PR.
=> update tests for tracers

src/thor-client.js, test/thorest-api/blocks/get-blocks.test.js
- added tests
- modified getBlock call
=> add tests for raw parameter

.github/workflows/run-e2e-tests.yaml
=> chore: gh action for `release` branches

.github/workflows/run-e2e-tests.yaml, test/evm/evm-methods.test.js, test/evm/individual-opcodes.test.js
Closes https://github.com/vechain/protocol-board-repo/issues/291
=> feat: Shanghai tests adapted

network/config/genesis.json
=> feat(galactica): fork starts in block 1

test/thorest-api/fees/get-fees-priority.test.js
Tests adapted to the new version
=> refactor: `priority/fees` endpoint

src/thor-client.js, src/transactions.js, test/thorest-api/transactions/fork/galactica/post-tx-negative.test.js, test/thorest-api/transactions/fork/galactica/post-tx-positive.test.js
| Test case  | Result |
| ------------- | ------------- |
| Send legacy and dyn fee txs after the fork  | ✅ |
| Legacy and dyn fee txs are shared among the nodes| ✅ |
=> Add send dyn fee tx - positive outcome

src/thor-client.js, test/thorest-api/fees/get-fees-history.test.js, test/thorest-api/fees/get-fees-priority.test.js, test/thorest-api/transactions/fork/galactica/post-tx-positive.test.js, test/thorest-api/transactions/setup/asserts.js
Title is self-explanatory. Removed unused method from the priority endpoint.
Closes https://github.com/vechain/protocol-board-repo/issues/510
=> feat: `fees/history` modified to include rewards + small refactor
